import type { NodeType } from "./roles";

/**
 * ============================================================================
 *  PERMISSION REGISTRY — the single source of truth for every permission node
 * ============================================================================
 *
 * Developers never write SQL for permissions again. Declare the node here,
 * once, and run the sync (Admin -> Roles & Permissions -> "Sync permissions",
 * or the `syncPermissions` server function). The synchroniser inserts what is
 * missing, updates what drifted and leaves everything else alone.
 *
 * Nothing in the engine knows any module name or key: keys are *derived* from
 * the nesting (`segment` values joined with "."), and the tree the Admin UI
 * renders is still read straight from the `permissions` table.
 *
 * Adding a permission:
 *
 *   {
 *     segment: "inventory",       // -> key "inventory"
 *     type: "MODULE",
 *     label: "Inventory",
 *     children: [
 *       { segment: "export", type: "BUTTON", label: "Export CSV" },  // -> "inventory.export"
 *     ],
 *   }
 */
export interface PermissionSpec {
  /** Key fragment appended to the parent's key. Omit only when `key` is given. */
  segment?: string;
  /** Escape hatch: absolute key when it cannot be derived from the parent. */
  key?: string;
  type: NodeType;
  label: string;
  description?: string;
  /** Free-form grouping used by the Admin filter (view / create / edit / ...). */
  category?: string;
  /** UI coordinates. Inherited from the parent when omitted. */
  page?: string;
  section?: string;
  tab?: string;
  card?: string;
  popup?: string;
  feature?: string;
  button?: string;
  /** True when the node maps to a backend write that RLS also enforces. */
  requiresBackend?: boolean;
  backendRef?: string;
  /** Sort order among siblings. Defaults to declaration order. */
  order?: number;
  children?: PermissionSpec[];
}

/** Identity helper — gives editors autocomplete without changing the data. */
export function definePermissions(specs: PermissionSpec[]): PermissionSpec[] {
  return specs;
}

export const PERMISSION_REGISTRY: PermissionSpec[] = definePermissions([
  {
    segment: "approvals",
    type: "MODULE",
    label: "Approvals",
    description: "View the approvals module.",
    category: "view",
    order: 1,
    children: [
      {
        segment: "create",
        type: "FEATURE",
        label: "Create Approvals",
        category: "create",
        feature: "Create Approvals",
        requiresBackend: true,
        order: 1,
      },
      {
        segment: "delete",
        type: "FEATURE",
        label: "Delete Approvals",
        category: "delete",
        feature: "Delete Approvals",
        requiresBackend: true,
        order: 2,
      },
      {
        segment: "edit",
        type: "FEATURE",
        label: "Edit Approvals",
        category: "edit",
        feature: "Edit Approvals",
        requiresBackend: true,
        order: 3,
      },
      {
        segment: "view",
        type: "FEATURE",
        label: "View Approvals",
        category: "view",
        feature: "View Approvals",
        requiresBackend: true,
        order: 4,
      },
    ],
  },
  {
    segment: "designs",
    type: "MODULE",
    label: "Designs",
    description: "View the designs module.",
    category: "view",
    order: 2,
    children: [
      {
        segment: "create",
        type: "FEATURE",
        label: "Create Designs",
        category: "create",
        feature: "Create Designs",
        requiresBackend: true,
        order: 5,
      },
      {
        segment: "delete",
        type: "FEATURE",
        label: "Delete Designs",
        category: "delete",
        feature: "Delete Designs",
        requiresBackend: true,
        order: 6,
      },
      {
        segment: "edit",
        type: "FEATURE",
        label: "Edit Designs",
        category: "edit",
        feature: "Edit Designs",
        requiresBackend: true,
        order: 7,
      },
      {
        segment: "view",
        type: "FEATURE",
        label: "View Designs",
        category: "view",
        feature: "View Designs",
        requiresBackend: true,
        order: 8,
      },
    ],
  },
  {
    segment: "inventory",
    type: "MODULE",
    label: "Inventory",
    description: "View the inventory module.",
    category: "view",
    order: 3,
    children: [
      {
        segment: "create",
        type: "FEATURE",
        label: "Create Inventory",
        category: "create",
        feature: "Create Inventory",
        requiresBackend: true,
        order: 9,
      },
      {
        segment: "delete",
        type: "FEATURE",
        label: "Delete Inventory",
        category: "delete",
        feature: "Delete Inventory",
        requiresBackend: true,
        order: 10,
      },
      {
        segment: "edit",
        type: "FEATURE",
        label: "Edit Inventory",
        category: "edit",
        feature: "Edit Inventory",
        requiresBackend: true,
        order: 11,
      },
      {
        segment: "view",
        type: "FEATURE",
        label: "View Inventory",
        category: "view",
        feature: "View Inventory",
        requiresBackend: true,
        order: 12,
      },
    ],
  },
  {
    segment: "lines",
    type: "MODULE",
    label: "Lines",
    description: "View the lines module.",
    category: "view",
    order: 4,
    children: [
      {
        segment: "create",
        type: "FEATURE",
        label: "Create Lines",
        category: "create",
        feature: "Create Lines",
        requiresBackend: true,
        order: 13,
      },
      {
        segment: "delete",
        type: "FEATURE",
        label: "Delete Lines",
        category: "delete",
        feature: "Delete Lines",
        requiresBackend: true,
        order: 14,
      },
      {
        segment: "edit",
        type: "FEATURE",
        label: "Edit Lines",
        category: "edit",
        feature: "Edit Lines",
        requiresBackend: true,
        order: 15,
      },
      {
        segment: "view",
        type: "FEATURE",
        label: "View Lines",
        category: "view",
        feature: "View Lines",
        requiresBackend: true,
        order: 16,
      },
    ],
  },
  {
    segment: "materials",
    type: "MODULE",
    label: "Materials",
    description: "View the materials module.",
    category: "view",
    order: 5,
    children: [
      {
        segment: "create",
        type: "FEATURE",
        label: "Create Materials",
        category: "create",
        feature: "Create Materials",
        requiresBackend: true,
        order: 17,
      },
      {
        segment: "delete",
        type: "FEATURE",
        label: "Delete Materials",
        category: "delete",
        feature: "Delete Materials",
        requiresBackend: true,
        order: 18,
      },
      {
        segment: "edit",
        type: "FEATURE",
        label: "Edit Materials",
        category: "edit",
        feature: "Edit Materials",
        requiresBackend: true,
        order: 19,
      },
      {
        segment: "view",
        type: "FEATURE",
        label: "View Materials",
        category: "view",
        feature: "View Materials",
        requiresBackend: true,
        order: 20,
      },
    ],
  },
  {
    segment: "production",
    type: "MODULE",
    label: "Production",
    description: "View the production module.",
    category: "view",
    order: 6,
    children: [
      {
        segment: "create",
        type: "FEATURE",
        label: "Create Production",
        category: "create",
        feature: "Create Production",
        requiresBackend: true,
        order: 21,
      },
      {
        segment: "delete",
        type: "FEATURE",
        label: "Delete Production",
        category: "delete",
        feature: "Delete Production",
        requiresBackend: true,
        order: 22,
      },
      {
        segment: "edit",
        type: "FEATURE",
        label: "Edit Production",
        category: "edit",
        feature: "Edit Production",
        requiresBackend: true,
        order: 23,
      },
      {
        segment: "view",
        type: "FEATURE",
        label: "View Production",
        category: "view",
        feature: "View Production",
        requiresBackend: true,
        order: 24,
      },
    ],
  },
  {
    segment: "reports",
    type: "MODULE",
    label: "Reports",
    description: "View the reports module.",
    category: "view",
    order: 7,
    children: [
      {
        segment: "create",
        type: "FEATURE",
        label: "Create Reports",
        category: "create",
        feature: "Create Reports",
        requiresBackend: true,
        order: 25,
      },
      {
        segment: "delete",
        type: "FEATURE",
        label: "Delete Reports",
        category: "delete",
        feature: "Delete Reports",
        requiresBackend: true,
        order: 26,
      },
      {
        segment: "edit",
        type: "FEATURE",
        label: "Edit Reports",
        category: "edit",
        feature: "Edit Reports",
        requiresBackend: true,
        order: 27,
      },
      {
        segment: "view",
        type: "FEATURE",
        label: "View Reports",
        category: "view",
        feature: "View Reports",
        requiresBackend: true,
        order: 28,
      },
    ],
  },
  {
    segment: "roles",
    type: "MODULE",
    label: "Roles",
    description: "View the roles module.",
    category: "view",
    order: 8,
    children: [
      {
        segment: "create",
        type: "FEATURE",
        label: "Create Roles",
        category: "create",
        feature: "Create Roles",
        requiresBackend: true,
        order: 29,
      },
      {
        segment: "delete",
        type: "FEATURE",
        label: "Delete Roles",
        category: "delete",
        feature: "Delete Roles",
        requiresBackend: true,
        order: 30,
      },
      {
        segment: "edit",
        type: "FEATURE",
        label: "Edit Roles",
        category: "edit",
        feature: "Edit Roles",
        requiresBackend: true,
        order: 31,
      },
      {
        segment: "view",
        type: "FEATURE",
        label: "View Roles",
        category: "view",
        feature: "View Roles",
        requiresBackend: true,
        order: 32,
      },
    ],
  },
  {
    segment: "samples",
    type: "MODULE",
    label: "Samples",
    description: "View the samples module.",
    category: "view",
    order: 9,
    children: [
      {
        segment: "detail",
        type: "PAGE",
        label: "Sample Development Detail",
        description: "View the per-design Sample Development detail page.",
        category: "view",
        page: "Sample Development Detail",
        order: 1,
        children: [
          {
            key: "samples.tab.making",
            type: "TAB",
            label: "Sample Making tab",
            description: "View the Sample Making tab.",
            category: "view",
            tab: "Sample Making",
            order: 1,
            children: [
              {
                key: "samples.card.running_operations",
                type: "CARD",
                label: "Running Operations card",
                description: "View the Running Operations card.",
                category: "view",
                card: "Running Operations",
                order: 1,
                children: [
                  {
                    key: "samples.operation.start",
                    type: "FEATURE",
                    label: "Start Operation",
                    description: "Start a new Sample Making operation.",
                    category: "start",
                    feature: "Start Operation",
                    requiresBackend: true,
                    backendRef: "workflow_steps insert",
                    order: 1,
                    children: [
                      {
                        segment: "button",
                        type: "BUTTON",
                        label: "+ Start Operation button",
                        description: "The button that opens the Start Operation flow.",
                        category: "start",
                        button: "+ Start Operation",
                        requiresBackend: true,
                        backendRef: "workflow_steps insert",
                        order: 1,
                        children: [
                          {
                            key: "samples.operation.start.action",
                            type: "BACKEND_ACTION",
                            label: "Insert workflow_steps row",
                            description: "The RLS-enforced write this button ultimately performs.",
                            category: "start",
                            requiresBackend: true,
                            backendRef: "workflow_steps insert (RLS)",
                            order: 1,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    key: "samples.operation.pause",
                    type: "FEATURE",
                    label: "Pause Operation",
                    description: "Pause Operation",
                    category: "pause",
                    feature: "Pause Operation",
                    requiresBackend: true,
                    backendRef: "workflow_steps update",
                    order: 2,
                  },
                  {
                    key: "samples.operation.resume",
                    type: "FEATURE",
                    label: "Resume Operation",
                    description: "Resume Operation",
                    category: "resume",
                    feature: "Resume Operation",
                    requiresBackend: true,
                    backendRef: "workflow_steps update",
                    order: 3,
                  },
                  {
                    key: "samples.operation.complete",
                    type: "FEATURE",
                    label: "Complete Operation",
                    description: "Complete Operation",
                    category: "complete",
                    feature: "Complete Operation",
                    requiresBackend: true,
                    backendRef: "workflow_steps update",
                    order: 4,
                  },
                  {
                    key: "samples.operation.cancel",
                    type: "FEATURE",
                    label: "Cancel Operation",
                    description: "Cancel Operation",
                    category: "cancel",
                    feature: "Cancel Operation",
                    requiresBackend: true,
                    backendRef: "workflow_steps delete",
                    order: 5,
                  },
                ],
              },
              {
                key: "samples.card.timeline",
                type: "CARD",
                label: "Workflow Timeline card",
                description: "View the Workflow Timeline card.",
                category: "view",
                card: "Workflow Timeline",
                order: 2,
                children: [
                  {
                    key: "samples.timeline.edit",
                    type: "FEATURE",
                    label: "Edit Timeline Entry",
                    description: "Edit Timeline Entry",
                    category: "edit",
                    feature: "Edit Timeline Entry",
                    requiresBackend: true,
                    backendRef: "workflow_steps update",
                    order: 1,
                  },
                  {
                    key: "samples.timeline.reopen",
                    type: "FEATURE",
                    label: "Reopen Step",
                    description: "Reopen Step",
                    category: "edit",
                    feature: "Reopen Step",
                    requiresBackend: true,
                    backendRef: "workflow_steps update",
                    order: 2,
                  },
                  {
                    key: "samples.timeline.delete",
                    type: "FEATURE",
                    label: "Soft-Delete Timeline Entry",
                    description: "Soft-Delete Timeline Entry",
                    category: "delete",
                    feature: "Soft-Delete Timeline Entry",
                    requiresBackend: true,
                    backendRef: "workflow_steps update (status=deleted)",
                    order: 3,
                  },
                ],
              },
              {
                key: "samples.popup.material_usage",
                type: "POPUP",
                label: "Material Usage Dialog",
                description: "Open the Material Usage dialog.",
                category: "view",
                popup: "Material Usage Dialog",
                order: 3,
                children: [
                  {
                    key: "samples.material_usage.confirm",
                    type: "FEATURE",
                    label: "Edit Material Usage",
                    description: "Confirm/edit material usage for this design.",
                    category: "edit",
                    feature: "Edit Material Usage",
                    requiresBackend: true,
                    backendRef: "design_materials replace",
                    order: 1,
                  },
                ],
              },
            ],
          },
          {
            key: "samples.tab.materials",
            type: "TAB",
            label: "Raw Materials tab",
            description: "View the Raw Materials tab.",
            category: "view",
            tab: "Raw Materials",
            order: 2,
            children: [
              {
                key: "samples.material.add",
                type: "FEATURE",
                label: "Add Material Selection",
                description: "Add Material Selection",
                category: "create",
                feature: "Add Material Selection",
                requiresBackend: true,
                backendRef: "design_materials insert",
                order: 1,
              },
              {
                key: "samples.material.edit",
                type: "FEATURE",
                label: "Edit Material Selection",
                description: "Edit Material Selection",
                category: "edit",
                feature: "Edit Material Selection",
                requiresBackend: true,
                backendRef: "design_materials update",
                order: 2,
              },
              {
                key: "samples.material.delete",
                type: "FEATURE",
                label: "Delete Material Selection",
                description: "Delete Material Selection",
                category: "delete",
                feature: "Delete Material Selection",
                requiresBackend: true,
                backendRef: "design_materials delete",
                order: 3,
              },
            ],
          },
          {
            key: "samples.tab.costing",
            type: "TAB",
            label: "Costing tab",
            description: "View the Costing tab.",
            category: "view",
            tab: "Costing",
            order: 3,
            children: [
              {
                key: "samples.costing.edit",
                type: "FEATURE",
                label: "Edit Overhead Cost",
                description: "Edit the Costing tab overhead line items.",
                category: "edit",
                feature: "Edit Overhead Cost",
                order: 1,
              },
            ],
          },
          {
            key: "samples.tab.approval",
            type: "TAB",
            label: "Approval tab",
            description: "View the Approval tab.",
            category: "view",
            tab: "Approval",
            order: 4,
            children: [
              {
                key: "samples.approval.approve",
                type: "FEATURE",
                label: "Record Approval",
                description: "Record Approval",
                category: "approve",
                feature: "Record Approval",
                requiresBackend: true,
                backendRef: "sample_approvals insert",
                order: 1,
              },
              {
                key: "samples.approval.withdraw",
                type: "FEATURE",
                label: "Withdraw Approval",
                description: "Withdraw Approval",
                category: "approve",
                feature: "Withdraw Approval",
                requiresBackend: true,
                backendRef: "withdraw_sample_approval RPC",
                order: 2,
              },
            ],
          },
        ],
      },
      {
        segment: "create",
        type: "FEATURE",
        label: "Create Samples",
        category: "create",
        feature: "Create Samples",
        requiresBackend: true,
        order: 33,
      },
      {
        segment: "delete",
        type: "FEATURE",
        label: "Delete Samples",
        category: "delete",
        feature: "Delete Samples",
        requiresBackend: true,
        order: 34,
      },
      {
        segment: "edit",
        type: "FEATURE",
        label: "Edit Samples",
        category: "edit",
        feature: "Edit Samples",
        requiresBackend: true,
        order: 35,
      },
      {
        segment: "view",
        type: "FEATURE",
        label: "View Samples",
        category: "view",
        feature: "View Samples",
        requiresBackend: true,
        order: 36,
      },
    ],
  },
  {
    segment: "settings",
    type: "MODULE",
    label: "Settings",
    description: "View the settings module.",
    category: "view",
    order: 10,
    children: [
      {
        segment: "create",
        type: "FEATURE",
        label: "Create Settings",
        category: "create",
        feature: "Create Settings",
        requiresBackend: true,
        order: 37,
      },
      {
        segment: "delete",
        type: "FEATURE",
        label: "Delete Settings",
        category: "delete",
        feature: "Delete Settings",
        requiresBackend: true,
        order: 38,
      },
      {
        segment: "edit",
        type: "FEATURE",
        label: "Edit Settings",
        category: "edit",
        feature: "Edit Settings",
        requiresBackend: true,
        order: 39,
      },
      {
        segment: "view",
        type: "FEATURE",
        label: "View Settings",
        category: "view",
        feature: "View Settings",
        requiresBackend: true,
        order: 40,
      },
    ],
  },
  {
    segment: "users",
    type: "MODULE",
    label: "Users",
    description: "View the users module.",
    category: "view",
    order: 11,
    children: [
      {
        segment: "create",
        type: "FEATURE",
        label: "Create Users",
        category: "create",
        feature: "Create Users",
        requiresBackend: true,
        order: 41,
      },
      {
        segment: "delete",
        type: "FEATURE",
        label: "Delete Users",
        category: "delete",
        feature: "Delete Users",
        requiresBackend: true,
        order: 42,
      },
      {
        segment: "edit",
        type: "FEATURE",
        label: "Edit Users",
        category: "edit",
        feature: "Edit Users",
        requiresBackend: true,
        order: 43,
      },
      {
        segment: "view",
        type: "FEATURE",
        label: "View Users",
        category: "view",
        feature: "View Users",
        requiresBackend: true,
        order: 44,
      },
    ],
  },
]);

