/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StockRouteImport } from './routes/stock'
import { Route as StitchingRouteImport } from './routes/stitching'
import { Route as SamplesRouteImport } from './routes/samples'
import { Route as SampleMakingRouteImport } from './routes/sample-making'
import { Route as SampleDevelopmentRouteImport } from './routes/sample-development'
import { Route as QcRouteImport } from './routes/qc'
import { Route as PackingRouteImport } from './routes/packing'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HandworkRouteImport } from './routes/handwork'
import { Route as CuttingRouteImport } from './routes/cutting'
import { Route as CostingRouteImport } from './routes/costing'
import { Route as BarcodeRouteImport } from './routes/barcode'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignsIndexRouteImport } from './routes/designs.index'
import { Route as DesignsCodeRouteImport } from './routes/designs.$code'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const StitchingRoute = StitchingRouteImport.update({
  id: '/stitching',
  path: '/stitching',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesRoute = SamplesRouteImport.update({
  id: '/samples',
  path: '/samples',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleMakingRoute = SampleMakingRouteImport.update({
  id: '/sample-making',
  path: '/sample-making',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleDevelopmentRoute = SampleDevelopmentRouteImport.update({
  id: '/sample-development',
  path: '/sample-development',
  getParentRoute: () => rootRouteImport,
} as any)
const QcRoute = QcRouteImport.update({
  id: '/qc',
  path: '/qc',
  getParentRoute: () => rootRouteImport,
} as any)
const PackingRoute = PackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HandworkRoute = HandworkRouteImport.update({
  id: '/handwork',
  path: '/handwork',
  getParentRoute: () => rootRouteImport,
} as any)
const CuttingRoute = CuttingRouteImport.update({
  id: '/cutting',
  path: '/cutting',
  getParentRoute: () => rootRouteImport,
} as any)
const CostingRoute = CostingRouteImport.update({
  id: '/costing',
  path: '/costing',
  getParentRoute: () => rootRouteImport,
} as any)
const BarcodeRoute = BarcodeRouteImport.update({
  id: '/barcode',
  path: '/barcode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsIndexRoute = DesignsIndexRouteImport.update({
  id: '/designs/',
  path: '/designs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsCodeRoute = DesignsCodeRouteImport.update({
  id: '/designs/$code',
  path: '/designs/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/barcode': typeof BarcodeRoute
  '/costing': typeof CostingRoute
  '/cutting': typeof CuttingRoute
  '/handwork': typeof HandworkRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/mcp': typeof McpRoute
  '/packing': typeof PackingRoute
  '/qc': typeof QcRoute
  '/sample-development': typeof SampleDevelopmentRoute
  '/sample-making': typeof SampleMakingRoute
  '/samples': typeof SamplesRoute
  '/stitching': typeof StitchingRoute
  '/stock': typeof StockRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/designs/$code': typeof DesignsCodeRoute
  '/designs/': typeof DesignsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/barcode': typeof BarcodeRoute
  '/costing': typeof CostingRoute
  '/cutting': typeof CuttingRoute
  '/handwork': typeof HandworkRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/mcp': typeof McpRoute
  '/packing': typeof PackingRoute
  '/qc': typeof QcRoute
  '/sample-development': typeof SampleDevelopmentRoute
  '/sample-making': typeof SampleMakingRoute
  '/samples': typeof SamplesRoute
  '/stitching': typeof StitchingRoute
  '/stock': typeof StockRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/designs/$code': typeof DesignsCodeRoute
  '/designs': typeof DesignsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/barcode': typeof BarcodeRoute
  '/costing': typeof CostingRoute
  '/cutting': typeof CuttingRoute
  '/handwork': typeof HandworkRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/mcp': typeof McpRoute
  '/packing': typeof PackingRoute
  '/qc': typeof QcRoute
  '/sample-development': typeof SampleDevelopmentRoute
  '/sample-making': typeof SampleMakingRoute
  '/samples': typeof SamplesRoute
  '/stitching': typeof StitchingRoute
  '/stock': typeof StockRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/designs/$code': typeof DesignsCodeRoute
  '/designs/': typeof DesignsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/barcode'
    | '/costing'
    | '/cutting'
    | '/handwork'
    | '/login'
    | '/materials'
    | '/mcp'
    | '/packing'
    | '/qc'
    | '/sample-development'
    | '/sample-making'
    | '/samples'
    | '/stitching'
    | '/stock'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/designs/$code'
    | '/designs/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/barcode'
    | '/costing'
    | '/cutting'
    | '/handwork'
    | '/login'
    | '/materials'
    | '/mcp'
    | '/packing'
    | '/qc'
    | '/sample-development'
    | '/sample-making'
    | '/samples'
    | '/stitching'
    | '/stock'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/designs/$code'
    | '/designs'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/barcode'
    | '/costing'
    | '/cutting'
    | '/handwork'
    | '/login'
    | '/materials'
    | '/mcp'
    | '/packing'
    | '/qc'
    | '/sample-development'
    | '/sample-making'
    | '/samples'
    | '/stitching'
    | '/stock'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/designs/$code'
    | '/designs/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  BarcodeRoute: typeof BarcodeRoute
  CostingRoute: typeof CostingRoute
  CuttingRoute: typeof CuttingRoute
  HandworkRoute: typeof HandworkRoute
  LoginRoute: typeof LoginRoute
  MaterialsRoute: typeof MaterialsRoute
  McpRoute: typeof McpRoute
  PackingRoute: typeof PackingRoute
  QcRoute: typeof QcRoute
  SampleDevelopmentRoute: typeof SampleDevelopmentRoute
  SampleMakingRoute: typeof SampleMakingRoute
  SamplesRoute: typeof SamplesRoute
  StitchingRoute: typeof StitchingRoute
  StockRoute: typeof StockRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DesignsCodeRoute: typeof DesignsCodeRoute
  DesignsIndexRoute: typeof DesignsIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stitching': {
      id: '/stitching'
      path: '/stitching'
      fullPath: '/stitching'
      preLoaderRoute: typeof StitchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples': {
      id: '/samples'
      path: '/samples'
      fullPath: '/samples'
      preLoaderRoute: typeof SamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample-making': {
      id: '/sample-making'
      path: '/sample-making'
      fullPath: '/sample-making'
      preLoaderRoute: typeof SampleMakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample-development': {
      id: '/sample-development'
      path: '/sample-development'
      fullPath: '/sample-development'
      preLoaderRoute: typeof SampleDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc': {
      id: '/qc'
      path: '/qc'
      fullPath: '/qc'
      preLoaderRoute: typeof QcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packing': {
      id: '/packing'
      path: '/packing'
      fullPath: '/packing'
      preLoaderRoute: typeof PackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handwork': {
      id: '/handwork'
      path: '/handwork'
      fullPath: '/handwork'
      preLoaderRoute: typeof HandworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cutting': {
      id: '/cutting'
      path: '/cutting'
      fullPath: '/cutting'
      preLoaderRoute: typeof CuttingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costing': {
      id: '/costing'
      path: '/costing'
      fullPath: '/costing'
      preLoaderRoute: typeof CostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barcode': {
      id: '/barcode'
      path: '/barcode'
      fullPath: '/barcode'
      preLoaderRoute: typeof BarcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs/': {
      id: '/designs/'
      path: '/designs'
      fullPath: '/designs/'
      preLoaderRoute: typeof DesignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs/$code': {
      id: '/designs/$code'
      path: '/designs/$code'
      fullPath: '/designs/$code'
      preLoaderRoute: typeof DesignsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  BarcodeRoute: BarcodeRoute,
  CostingRoute: CostingRoute,
  CuttingRoute: CuttingRoute,
  HandworkRoute: HandworkRoute,
  LoginRoute: LoginRoute,
  MaterialsRoute: MaterialsRoute,
  McpRoute: McpRoute,
  PackingRoute: PackingRoute,
  QcRoute: QcRoute,
  SampleDevelopmentRoute: SampleDevelopmentRoute,
  SampleMakingRoute: SampleMakingRoute,
  SamplesRoute: SamplesRoute,
  StitchingRoute: StitchingRoute,
  StockRoute: StockRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DesignsCodeRoute: DesignsCodeRoute,
  DesignsIndexRoute: DesignsIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
