/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StockRouteImport } from './routes/stock'
import { Route as StitchingRouteImport } from './routes/stitching'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SamplesRouteImport } from './routes/samples'
import { Route as SampleMakingRouteImport } from './routes/sample-making'
import { Route as QcRouteImport } from './routes/qc'
import { Route as PackingRouteImport } from './routes/packing'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HandworkRouteImport } from './routes/handwork'
import { Route as CuttingRouteImport } from './routes/cutting'
import { Route as CostingRouteImport } from './routes/costing'
import { Route as BarcodeRouteImport } from './routes/barcode'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SampleDevelopmentIndexRouteImport } from './routes/sample-development.index'
import { Route as ProductionIndexRouteImport } from './routes/production.index'
import { Route as LinesIndexRouteImport } from './routes/lines.index'
import { Route as DesignsIndexRouteImport } from './routes/designs.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SettingsWorkstationsRouteImport } from './routes/settings.workstations'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as SettingsThemeRouteImport } from './routes/settings.theme'
import { Route as SettingsSystemRouteImport } from './routes/settings.system'
import { Route as SettingsStructureRouteImport } from './routes/settings.structure'
import { Route as SettingsRolesRouteImport } from './routes/settings.roles'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsPhotoRouteImport } from './routes/settings.photo'
import { Route as SettingsPasswordRouteImport } from './routes/settings.password'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsCompanyRouteImport } from './routes/settings.company'
import { Route as SampleDevelopmentCodeRouteImport } from './routes/sample-development.$code'
import { Route as ProductionPoRouteImport } from './routes/production.$po'
import { Route as LinesLineRouteImport } from './routes/lines.$line'
import { Route as DesignsCodeRouteImport } from './routes/designs.$code'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as DesignsCodeWorkflowRouteImport } from './routes/designs.$code.workflow'

const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const StitchingRoute = StitchingRouteImport.update({
  id: '/stitching',
  path: '/stitching',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesRoute = SamplesRouteImport.update({
  id: '/samples',
  path: '/samples',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleMakingRoute = SampleMakingRouteImport.update({
  id: '/sample-making',
  path: '/sample-making',
  getParentRoute: () => rootRouteImport,
} as any)
const QcRoute = QcRouteImport.update({
  id: '/qc',
  path: '/qc',
  getParentRoute: () => rootRouteImport,
} as any)
const PackingRoute = PackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HandworkRoute = HandworkRouteImport.update({
  id: '/handwork',
  path: '/handwork',
  getParentRoute: () => rootRouteImport,
} as any)
const CuttingRoute = CuttingRouteImport.update({
  id: '/cutting',
  path: '/cutting',
  getParentRoute: () => rootRouteImport,
} as any)
const CostingRoute = CostingRouteImport.update({
  id: '/costing',
  path: '/costing',
  getParentRoute: () => rootRouteImport,
} as any)
const BarcodeRoute = BarcodeRouteImport.update({
  id: '/barcode',
  path: '/barcode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SampleDevelopmentIndexRoute = SampleDevelopmentIndexRouteImport.update({
  id: '/sample-development/',
  path: '/sample-development/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionIndexRoute = ProductionIndexRouteImport.update({
  id: '/production/',
  path: '/production/',
  getParentRoute: () => rootRouteImport,
} as any)
const LinesIndexRoute = LinesIndexRouteImport.update({
  id: '/lines/',
  path: '/lines/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsIndexRoute = DesignsIndexRouteImport.update({
  id: '/designs/',
  path: '/designs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SettingsWorkstationsRoute = SettingsWorkstationsRouteImport.update({
  id: '/workstations',
  path: '/workstations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsThemeRoute = SettingsThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSystemRoute = SettingsSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsStructureRoute = SettingsStructureRouteImport.update({
  id: '/structure',
  path: '/structure',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRolesRoute = SettingsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPhotoRoute = SettingsPhotoRouteImport.update({
  id: '/photo',
  path: '/photo',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPasswordRoute = SettingsPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCompanyRoute = SettingsCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => SettingsRoute,
} as any)
const SampleDevelopmentCodeRoute = SampleDevelopmentCodeRouteImport.update({
  id: '/sample-development/$code',
  path: '/sample-development/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionPoRoute = ProductionPoRouteImport.update({
  id: '/production/$po',
  path: '/production/$po',
  getParentRoute: () => rootRouteImport,
} as any)
const LinesLineRoute = LinesLineRouteImport.update({
  id: '/lines/$line',
  path: '/lines/$line',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsCodeRoute = DesignsCodeRouteImport.update({
  id: '/designs/$code',
  path: '/designs/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const DesignsCodeWorkflowRoute = DesignsCodeWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => DesignsCodeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/barcode': typeof BarcodeRoute
  '/costing': typeof CostingRoute
  '/cutting': typeof CuttingRoute
  '/handwork': typeof HandworkRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/packing': typeof PackingRoute
  '/qc': typeof QcRoute
  '/sample-making': typeof SampleMakingRoute
  '/samples': typeof SamplesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/stitching': typeof StitchingRoute
  '/stock': typeof StockRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/designs/$code': typeof DesignsCodeRouteWithChildren
  '/lines/$line': typeof LinesLineRoute
  '/production/$po': typeof ProductionPoRoute
  '/sample-development/$code': typeof SampleDevelopmentCodeRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/password': typeof SettingsPasswordRoute
  '/settings/photo': typeof SettingsPhotoRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/structure': typeof SettingsStructureRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/workstations': typeof SettingsWorkstationsRoute
  '/admin/': typeof AdminIndexRoute
  '/designs/': typeof DesignsIndexRoute
  '/lines/': typeof LinesIndexRoute
  '/production/': typeof ProductionIndexRoute
  '/sample-development/': typeof SampleDevelopmentIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/designs/$code/workflow': typeof DesignsCodeWorkflowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/barcode': typeof BarcodeRoute
  '/costing': typeof CostingRoute
  '/cutting': typeof CuttingRoute
  '/handwork': typeof HandworkRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/packing': typeof PackingRoute
  '/qc': typeof QcRoute
  '/sample-making': typeof SampleMakingRoute
  '/samples': typeof SamplesRoute
  '/stitching': typeof StitchingRoute
  '/stock': typeof StockRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/designs/$code': typeof DesignsCodeRouteWithChildren
  '/lines/$line': typeof LinesLineRoute
  '/production/$po': typeof ProductionPoRoute
  '/sample-development/$code': typeof SampleDevelopmentCodeRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/password': typeof SettingsPasswordRoute
  '/settings/photo': typeof SettingsPhotoRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/structure': typeof SettingsStructureRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/workstations': typeof SettingsWorkstationsRoute
  '/admin': typeof AdminIndexRoute
  '/designs': typeof DesignsIndexRoute
  '/lines': typeof LinesIndexRoute
  '/production': typeof ProductionIndexRoute
  '/sample-development': typeof SampleDevelopmentIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/designs/$code/workflow': typeof DesignsCodeWorkflowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/barcode': typeof BarcodeRoute
  '/costing': typeof CostingRoute
  '/cutting': typeof CuttingRoute
  '/handwork': typeof HandworkRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/packing': typeof PackingRoute
  '/qc': typeof QcRoute
  '/sample-making': typeof SampleMakingRoute
  '/samples': typeof SamplesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/stitching': typeof StitchingRoute
  '/stock': typeof StockRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/designs/$code': typeof DesignsCodeRouteWithChildren
  '/lines/$line': typeof LinesLineRoute
  '/production/$po': typeof ProductionPoRoute
  '/sample-development/$code': typeof SampleDevelopmentCodeRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/password': typeof SettingsPasswordRoute
  '/settings/photo': typeof SettingsPhotoRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/structure': typeof SettingsStructureRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/workstations': typeof SettingsWorkstationsRoute
  '/admin/': typeof AdminIndexRoute
  '/designs/': typeof DesignsIndexRoute
  '/lines/': typeof LinesIndexRoute
  '/production/': typeof ProductionIndexRoute
  '/sample-development/': typeof SampleDevelopmentIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/designs/$code/workflow': typeof DesignsCodeWorkflowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/approvals'
    | '/barcode'
    | '/costing'
    | '/cutting'
    | '/handwork'
    | '/inventory'
    | '/login'
    | '/materials'
    | '/packing'
    | '/qc'
    | '/sample-making'
    | '/samples'
    | '/settings'
    | '/stitching'
    | '/stock'
    | '/admin/roles'
    | '/admin/users'
    | '/designs/$code'
    | '/lines/$line'
    | '/production/$po'
    | '/sample-development/$code'
    | '/settings/company'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/password'
    | '/settings/photo'
    | '/settings/profile'
    | '/settings/roles'
    | '/settings/structure'
    | '/settings/system'
    | '/settings/theme'
    | '/settings/users'
    | '/settings/workstations'
    | '/admin/'
    | '/designs/'
    | '/lines/'
    | '/production/'
    | '/sample-development/'
    | '/settings/'
    | '/designs/$code/workflow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/barcode'
    | '/costing'
    | '/cutting'
    | '/handwork'
    | '/inventory'
    | '/login'
    | '/materials'
    | '/packing'
    | '/qc'
    | '/sample-making'
    | '/samples'
    | '/stitching'
    | '/stock'
    | '/admin/roles'
    | '/admin/users'
    | '/designs/$code'
    | '/lines/$line'
    | '/production/$po'
    | '/sample-development/$code'
    | '/settings/company'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/password'
    | '/settings/photo'
    | '/settings/profile'
    | '/settings/roles'
    | '/settings/structure'
    | '/settings/system'
    | '/settings/theme'
    | '/settings/users'
    | '/settings/workstations'
    | '/admin'
    | '/designs'
    | '/lines'
    | '/production'
    | '/sample-development'
    | '/settings'
    | '/designs/$code/workflow'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/approvals'
    | '/barcode'
    | '/costing'
    | '/cutting'
    | '/handwork'
    | '/inventory'
    | '/login'
    | '/materials'
    | '/packing'
    | '/qc'
    | '/sample-making'
    | '/samples'
    | '/settings'
    | '/stitching'
    | '/stock'
    | '/admin/roles'
    | '/admin/users'
    | '/designs/$code'
    | '/lines/$line'
    | '/production/$po'
    | '/sample-development/$code'
    | '/settings/company'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/password'
    | '/settings/photo'
    | '/settings/profile'
    | '/settings/roles'
    | '/settings/structure'
    | '/settings/system'
    | '/settings/theme'
    | '/settings/users'
    | '/settings/workstations'
    | '/admin/'
    | '/designs/'
    | '/lines/'
    | '/production/'
    | '/sample-development/'
    | '/settings/'
    | '/designs/$code/workflow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApprovalsRoute: typeof ApprovalsRoute
  BarcodeRoute: typeof BarcodeRoute
  CostingRoute: typeof CostingRoute
  CuttingRoute: typeof CuttingRoute
  HandworkRoute: typeof HandworkRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  MaterialsRoute: typeof MaterialsRoute
  PackingRoute: typeof PackingRoute
  QcRoute: typeof QcRoute
  SampleMakingRoute: typeof SampleMakingRoute
  SamplesRoute: typeof SamplesRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  StitchingRoute: typeof StitchingRoute
  StockRoute: typeof StockRoute
  DesignsCodeRoute: typeof DesignsCodeRouteWithChildren
  LinesLineRoute: typeof LinesLineRoute
  ProductionPoRoute: typeof ProductionPoRoute
  SampleDevelopmentCodeRoute: typeof SampleDevelopmentCodeRoute
  DesignsIndexRoute: typeof DesignsIndexRoute
  LinesIndexRoute: typeof LinesIndexRoute
  ProductionIndexRoute: typeof ProductionIndexRoute
  SampleDevelopmentIndexRoute: typeof SampleDevelopmentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stitching': {
      id: '/stitching'
      path: '/stitching'
      fullPath: '/stitching'
      preLoaderRoute: typeof StitchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples': {
      id: '/samples'
      path: '/samples'
      fullPath: '/samples'
      preLoaderRoute: typeof SamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample-making': {
      id: '/sample-making'
      path: '/sample-making'
      fullPath: '/sample-making'
      preLoaderRoute: typeof SampleMakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc': {
      id: '/qc'
      path: '/qc'
      fullPath: '/qc'
      preLoaderRoute: typeof QcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packing': {
      id: '/packing'
      path: '/packing'
      fullPath: '/packing'
      preLoaderRoute: typeof PackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handwork': {
      id: '/handwork'
      path: '/handwork'
      fullPath: '/handwork'
      preLoaderRoute: typeof HandworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cutting': {
      id: '/cutting'
      path: '/cutting'
      fullPath: '/cutting'
      preLoaderRoute: typeof CuttingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costing': {
      id: '/costing'
      path: '/costing'
      fullPath: '/costing'
      preLoaderRoute: typeof CostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barcode': {
      id: '/barcode'
      path: '/barcode'
      fullPath: '/barcode'
      preLoaderRoute: typeof BarcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/sample-development/': {
      id: '/sample-development/'
      path: '/sample-development'
      fullPath: '/sample-development/'
      preLoaderRoute: typeof SampleDevelopmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/': {
      id: '/production/'
      path: '/production'
      fullPath: '/production/'
      preLoaderRoute: typeof ProductionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lines/': {
      id: '/lines/'
      path: '/lines'
      fullPath: '/lines/'
      preLoaderRoute: typeof LinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs/': {
      id: '/designs/'
      path: '/designs'
      fullPath: '/designs/'
      preLoaderRoute: typeof DesignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/settings/workstations': {
      id: '/settings/workstations'
      path: '/workstations'
      fullPath: '/settings/workstations'
      preLoaderRoute: typeof SettingsWorkstationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/theme': {
      id: '/settings/theme'
      path: '/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof SettingsThemeRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/system': {
      id: '/settings/system'
      path: '/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof SettingsSystemRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/structure': {
      id: '/settings/structure'
      path: '/structure'
      fullPath: '/settings/structure'
      preLoaderRoute: typeof SettingsStructureRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/roles': {
      id: '/settings/roles'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof SettingsRolesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/photo': {
      id: '/settings/photo'
      path: '/photo'
      fullPath: '/settings/photo'
      preLoaderRoute: typeof SettingsPhotoRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/password': {
      id: '/settings/password'
      path: '/password'
      fullPath: '/settings/password'
      preLoaderRoute: typeof SettingsPasswordRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/company': {
      id: '/settings/company'
      path: '/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof SettingsCompanyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/sample-development/$code': {
      id: '/sample-development/$code'
      path: '/sample-development/$code'
      fullPath: '/sample-development/$code'
      preLoaderRoute: typeof SampleDevelopmentCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/$po': {
      id: '/production/$po'
      path: '/production/$po'
      fullPath: '/production/$po'
      preLoaderRoute: typeof ProductionPoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lines/$line': {
      id: '/lines/$line'
      path: '/lines/$line'
      fullPath: '/lines/$line'
      preLoaderRoute: typeof LinesLineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs/$code': {
      id: '/designs/$code'
      path: '/designs/$code'
      fullPath: '/designs/$code'
      preLoaderRoute: typeof DesignsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/designs/$code/workflow': {
      id: '/designs/$code/workflow'
      path: '/workflow'
      fullPath: '/designs/$code/workflow'
      preLoaderRoute: typeof DesignsCodeWorkflowRouteImport
      parentRoute: typeof DesignsCodeRoute
    }
  }
}

interface AdminRouteChildren {
  AdminRolesRoute: typeof AdminRolesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminRolesRoute: AdminRolesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SettingsRouteChildren {
  SettingsCompanyRoute: typeof SettingsCompanyRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPasswordRoute: typeof SettingsPasswordRoute
  SettingsPhotoRoute: typeof SettingsPhotoRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsRolesRoute: typeof SettingsRolesRoute
  SettingsStructureRoute: typeof SettingsStructureRoute
  SettingsSystemRoute: typeof SettingsSystemRoute
  SettingsThemeRoute: typeof SettingsThemeRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  SettingsWorkstationsRoute: typeof SettingsWorkstationsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsCompanyRoute: SettingsCompanyRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPasswordRoute: SettingsPasswordRoute,
  SettingsPhotoRoute: SettingsPhotoRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsRolesRoute: SettingsRolesRoute,
  SettingsStructureRoute: SettingsStructureRoute,
  SettingsSystemRoute: SettingsSystemRoute,
  SettingsThemeRoute: SettingsThemeRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  SettingsWorkstationsRoute: SettingsWorkstationsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface DesignsCodeRouteChildren {
  DesignsCodeWorkflowRoute: typeof DesignsCodeWorkflowRoute
}

const DesignsCodeRouteChildren: DesignsCodeRouteChildren = {
  DesignsCodeWorkflowRoute: DesignsCodeWorkflowRoute,
}

const DesignsCodeRouteWithChildren = DesignsCodeRoute._addFileChildren(
  DesignsCodeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApprovalsRoute: ApprovalsRoute,
  BarcodeRoute: BarcodeRoute,
  CostingRoute: CostingRoute,
  CuttingRoute: CuttingRoute,
  HandworkRoute: HandworkRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  MaterialsRoute: MaterialsRoute,
  PackingRoute: PackingRoute,
  QcRoute: QcRoute,
  SampleMakingRoute: SampleMakingRoute,
  SamplesRoute: SamplesRoute,
  SettingsRoute: SettingsRouteWithChildren,
  StitchingRoute: StitchingRoute,
  StockRoute: StockRoute,
  DesignsCodeRoute: DesignsCodeRouteWithChildren,
  LinesLineRoute: LinesLineRoute,
  ProductionPoRoute: ProductionPoRoute,
  SampleDevelopmentCodeRoute: SampleDevelopmentCodeRoute,
  DesignsIndexRoute: DesignsIndexRoute,
  LinesIndexRoute: LinesIndexRoute,
  ProductionIndexRoute: ProductionIndexRoute,
  SampleDevelopmentIndexRoute: SampleDevelopmentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
