/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StockRouteImport } from './routes/stock'
import { Route as StitchingRouteImport } from './routes/stitching'
import { Route as SamplesRouteImport } from './routes/samples'
import { Route as SampleMakingRouteImport } from './routes/sample-making'
import { Route as QcRouteImport } from './routes/qc'
import { Route as PackingRouteImport } from './routes/packing'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HandworkRouteImport } from './routes/handwork'
import { Route as CuttingRouteImport } from './routes/cutting'
import { Route as CostingRouteImport } from './routes/costing'
import { Route as BarcodeRouteImport } from './routes/barcode'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SampleDevelopmentIndexRouteImport } from './routes/sample-development.index'
import { Route as ProductionIndexRouteImport } from './routes/production.index'
import { Route as DesignsIndexRouteImport } from './routes/designs.index'
import { Route as SampleDevelopmentCodeRouteImport } from './routes/sample-development.$code'
import { Route as ProductionReadyRouteImport } from './routes/production.ready'
import { Route as ProductionPoRouteImport } from './routes/production.$po'
import { Route as DesignsCodeRouteImport } from './routes/designs.$code'
import { Route as DesignsCodeWorkflowRouteImport } from './routes/designs.$code.workflow'

const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const StitchingRoute = StitchingRouteImport.update({
  id: '/stitching',
  path: '/stitching',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesRoute = SamplesRouteImport.update({
  id: '/samples',
  path: '/samples',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleMakingRoute = SampleMakingRouteImport.update({
  id: '/sample-making',
  path: '/sample-making',
  getParentRoute: () => rootRouteImport,
} as any)
const QcRoute = QcRouteImport.update({
  id: '/qc',
  path: '/qc',
  getParentRoute: () => rootRouteImport,
} as any)
const PackingRoute = PackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HandworkRoute = HandworkRouteImport.update({
  id: '/handwork',
  path: '/handwork',
  getParentRoute: () => rootRouteImport,
} as any)
const CuttingRoute = CuttingRouteImport.update({
  id: '/cutting',
  path: '/cutting',
  getParentRoute: () => rootRouteImport,
} as any)
const CostingRoute = CostingRouteImport.update({
  id: '/costing',
  path: '/costing',
  getParentRoute: () => rootRouteImport,
} as any)
const BarcodeRoute = BarcodeRouteImport.update({
  id: '/barcode',
  path: '/barcode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleDevelopmentIndexRoute = SampleDevelopmentIndexRouteImport.update({
  id: '/sample-development/',
  path: '/sample-development/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionIndexRoute = ProductionIndexRouteImport.update({
  id: '/production/',
  path: '/production/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsIndexRoute = DesignsIndexRouteImport.update({
  id: '/designs/',
  path: '/designs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleDevelopmentCodeRoute = SampleDevelopmentCodeRouteImport.update({
  id: '/sample-development/$code',
  path: '/sample-development/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionReadyRoute = ProductionReadyRouteImport.update({
  id: '/production/ready',
  path: '/production/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionPoRoute = ProductionPoRouteImport.update({
  id: '/production/$po',
  path: '/production/$po',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsCodeRoute = DesignsCodeRouteImport.update({
  id: '/designs/$code',
  path: '/designs/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsCodeWorkflowRoute = DesignsCodeWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => DesignsCodeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/barcode': typeof BarcodeRoute
  '/costing': typeof CostingRoute
  '/cutting': typeof CuttingRoute
  '/handwork': typeof HandworkRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/packing': typeof PackingRoute
  '/qc': typeof QcRoute
  '/sample-making': typeof SampleMakingRoute
  '/samples': typeof SamplesRoute
  '/stitching': typeof StitchingRoute
  '/stock': typeof StockRoute
  '/designs/$code': typeof DesignsCodeRouteWithChildren
  '/production/$po': typeof ProductionPoRoute
  '/production/ready': typeof ProductionReadyRoute
  '/sample-development/$code': typeof SampleDevelopmentCodeRoute
  '/designs/': typeof DesignsIndexRoute
  '/production/': typeof ProductionIndexRoute
  '/sample-development/': typeof SampleDevelopmentIndexRoute
  '/designs/$code/workflow': typeof DesignsCodeWorkflowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/barcode': typeof BarcodeRoute
  '/costing': typeof CostingRoute
  '/cutting': typeof CuttingRoute
  '/handwork': typeof HandworkRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/packing': typeof PackingRoute
  '/qc': typeof QcRoute
  '/sample-making': typeof SampleMakingRoute
  '/samples': typeof SamplesRoute
  '/stitching': typeof StitchingRoute
  '/stock': typeof StockRoute
  '/designs/$code': typeof DesignsCodeRouteWithChildren
  '/production/$po': typeof ProductionPoRoute
  '/production/ready': typeof ProductionReadyRoute
  '/sample-development/$code': typeof SampleDevelopmentCodeRoute
  '/designs': typeof DesignsIndexRoute
  '/production': typeof ProductionIndexRoute
  '/sample-development': typeof SampleDevelopmentIndexRoute
  '/designs/$code/workflow': typeof DesignsCodeWorkflowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/barcode': typeof BarcodeRoute
  '/costing': typeof CostingRoute
  '/cutting': typeof CuttingRoute
  '/handwork': typeof HandworkRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/packing': typeof PackingRoute
  '/qc': typeof QcRoute
  '/sample-making': typeof SampleMakingRoute
  '/samples': typeof SamplesRoute
  '/stitching': typeof StitchingRoute
  '/stock': typeof StockRoute
  '/designs/$code': typeof DesignsCodeRouteWithChildren
  '/production/$po': typeof ProductionPoRoute
  '/production/ready': typeof ProductionReadyRoute
  '/sample-development/$code': typeof SampleDevelopmentCodeRoute
  '/designs/': typeof DesignsIndexRoute
  '/production/': typeof ProductionIndexRoute
  '/sample-development/': typeof SampleDevelopmentIndexRoute
  '/designs/$code/workflow': typeof DesignsCodeWorkflowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/barcode'
    | '/costing'
    | '/cutting'
    | '/handwork'
    | '/inventory'
    | '/login'
    | '/materials'
    | '/packing'
    | '/qc'
    | '/sample-making'
    | '/samples'
    | '/stitching'
    | '/stock'
    | '/designs/$code'
    | '/production/$po'
    | '/production/ready'
    | '/sample-development/$code'
    | '/designs/'
    | '/production/'
    | '/sample-development/'
    | '/designs/$code/workflow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/barcode'
    | '/costing'
    | '/cutting'
    | '/handwork'
    | '/inventory'
    | '/login'
    | '/materials'
    | '/packing'
    | '/qc'
    | '/sample-making'
    | '/samples'
    | '/stitching'
    | '/stock'
    | '/designs/$code'
    | '/production/$po'
    | '/production/ready'
    | '/sample-development/$code'
    | '/designs'
    | '/production'
    | '/sample-development'
    | '/designs/$code/workflow'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/barcode'
    | '/costing'
    | '/cutting'
    | '/handwork'
    | '/inventory'
    | '/login'
    | '/materials'
    | '/packing'
    | '/qc'
    | '/sample-making'
    | '/samples'
    | '/stitching'
    | '/stock'
    | '/designs/$code'
    | '/production/$po'
    | '/production/ready'
    | '/sample-development/$code'
    | '/designs/'
    | '/production/'
    | '/sample-development/'
    | '/designs/$code/workflow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  BarcodeRoute: typeof BarcodeRoute
  CostingRoute: typeof CostingRoute
  CuttingRoute: typeof CuttingRoute
  HandworkRoute: typeof HandworkRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  MaterialsRoute: typeof MaterialsRoute
  PackingRoute: typeof PackingRoute
  QcRoute: typeof QcRoute
  SampleMakingRoute: typeof SampleMakingRoute
  SamplesRoute: typeof SamplesRoute
  StitchingRoute: typeof StitchingRoute
  StockRoute: typeof StockRoute
  DesignsCodeRoute: typeof DesignsCodeRouteWithChildren
  ProductionPoRoute: typeof ProductionPoRoute
  ProductionReadyRoute: typeof ProductionReadyRoute
  SampleDevelopmentCodeRoute: typeof SampleDevelopmentCodeRoute
  DesignsIndexRoute: typeof DesignsIndexRoute
  ProductionIndexRoute: typeof ProductionIndexRoute
  SampleDevelopmentIndexRoute: typeof SampleDevelopmentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stitching': {
      id: '/stitching'
      path: '/stitching'
      fullPath: '/stitching'
      preLoaderRoute: typeof StitchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples': {
      id: '/samples'
      path: '/samples'
      fullPath: '/samples'
      preLoaderRoute: typeof SamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample-making': {
      id: '/sample-making'
      path: '/sample-making'
      fullPath: '/sample-making'
      preLoaderRoute: typeof SampleMakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc': {
      id: '/qc'
      path: '/qc'
      fullPath: '/qc'
      preLoaderRoute: typeof QcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packing': {
      id: '/packing'
      path: '/packing'
      fullPath: '/packing'
      preLoaderRoute: typeof PackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handwork': {
      id: '/handwork'
      path: '/handwork'
      fullPath: '/handwork'
      preLoaderRoute: typeof HandworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cutting': {
      id: '/cutting'
      path: '/cutting'
      fullPath: '/cutting'
      preLoaderRoute: typeof CuttingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costing': {
      id: '/costing'
      path: '/costing'
      fullPath: '/costing'
      preLoaderRoute: typeof CostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barcode': {
      id: '/barcode'
      path: '/barcode'
      fullPath: '/barcode'
      preLoaderRoute: typeof BarcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample-development/': {
      id: '/sample-development/'
      path: '/sample-development'
      fullPath: '/sample-development/'
      preLoaderRoute: typeof SampleDevelopmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/': {
      id: '/production/'
      path: '/production'
      fullPath: '/production/'
      preLoaderRoute: typeof ProductionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs/': {
      id: '/designs/'
      path: '/designs'
      fullPath: '/designs/'
      preLoaderRoute: typeof DesignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample-development/$code': {
      id: '/sample-development/$code'
      path: '/sample-development/$code'
      fullPath: '/sample-development/$code'
      preLoaderRoute: typeof SampleDevelopmentCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/ready': {
      id: '/production/ready'
      path: '/production/ready'
      fullPath: '/production/ready'
      preLoaderRoute: typeof ProductionReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/$po': {
      id: '/production/$po'
      path: '/production/$po'
      fullPath: '/production/$po'
      preLoaderRoute: typeof ProductionPoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs/$code': {
      id: '/designs/$code'
      path: '/designs/$code'
      fullPath: '/designs/$code'
      preLoaderRoute: typeof DesignsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs/$code/workflow': {
      id: '/designs/$code/workflow'
      path: '/workflow'
      fullPath: '/designs/$code/workflow'
      preLoaderRoute: typeof DesignsCodeWorkflowRouteImport
      parentRoute: typeof DesignsCodeRoute
    }
  }
}

interface DesignsCodeRouteChildren {
  DesignsCodeWorkflowRoute: typeof DesignsCodeWorkflowRoute
}

const DesignsCodeRouteChildren: DesignsCodeRouteChildren = {
  DesignsCodeWorkflowRoute: DesignsCodeWorkflowRoute,
}

const DesignsCodeRouteWithChildren = DesignsCodeRoute._addFileChildren(
  DesignsCodeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  BarcodeRoute: BarcodeRoute,
  CostingRoute: CostingRoute,
  CuttingRoute: CuttingRoute,
  HandworkRoute: HandworkRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  MaterialsRoute: MaterialsRoute,
  PackingRoute: PackingRoute,
  QcRoute: QcRoute,
  SampleMakingRoute: SampleMakingRoute,
  SamplesRoute: SamplesRoute,
  StitchingRoute: StitchingRoute,
  StockRoute: StockRoute,
  DesignsCodeRoute: DesignsCodeRouteWithChildren,
  ProductionPoRoute: ProductionPoRoute,
  ProductionReadyRoute: ProductionReadyRoute,
  SampleDevelopmentCodeRoute: SampleDevelopmentCodeRoute,
  DesignsIndexRoute: DesignsIndexRoute,
  ProductionIndexRoute: ProductionIndexRoute,
  SampleDevelopmentIndexRoute: SampleDevelopmentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
